// export const synonymMap = {
//   flights: ["flight", "air travel", "domestic flights", "international flights", "flight booking", "plane"],
//   hotels: ["hotel", "stay", "lodging", "accommodation"],
//   lounge: ["lounge", "airport lounge", "domestic lounge", "international lounge"],
//   train: ["railway", "train ticket", "irctc"],
//   metro: ["metro", "subway", "metro rail", "urban rail"],
//   bus: ["bus", "roadways", "bus travel"],
//   movies: ["movie", "cinema", "entertainment", "movie tickets"],
//   dining: ["food", "restaurant", "eating out", "meal"],
//   shopping: ["shopping", "retail", "online shopping", "offline shopping", "e-commerce", "amazon", "flipkart"],
//   fuel: ["fuel", "petrol", "diesel", "fuel station", "fuel surcharge waiver"],
//   grocery: ["grocery", "supermarket", "departmental store", "grocery stores"],
//   utilities: ["bill payment", "electricity", "water", "mobile recharge"],
//   insurance: ["insurance", "air accident", "travel insurance", "medical cover", "fraud protection"],
//   voucher: ["voucher", "discount voucher", "gift voucher", "amazon voucher", "flight voucher"],
//   milestone: ["milestone", "spending milestone", "annual spend", "quarterly spend"],
//   waiver: ["waiver", "fee waiver", "joining fee waiver", "annual fee waiver"],
//   rewards: ["rewards", "reward points", "rp", "points", "cv points", "6e rewards"],
//   welcome: ["welcome bonus", "joining gift", "welcome gift", "signup bonus"]
// };


// 

export const synonymMap = {
  entertainment: [
    "add-on card",
    "bookmyshow weekend offer",
    "dining",
    "entertainment",
    "general travel",
    "golf access",
    "golf games worldwide",
    "mini app",
    "movies",
    "paytm mall"
  ],
  dining: [
    "ajio",
    "big basket",
    "bigbasket",
    "dineout passport (25% off)",
    "dineout pay",
    "diners exclusive offers",
    "dining",
    "dining and grocery",
    "dmart purchases",
    "entertainment",
    "general travel",
    "good food trail",
    "good food trail dining",
    "good food trail program",
    "partner restaurants",
    "partner restaurants via dineout",
    "premium restaurants",
    "restaurant dining",
    "restaurant spend",
    "restaurant spends",
    "restaurants",
    "restaurants and eating places",
    "restaurants via swiggy dineout",
    "spend tracking",
    "swiggy",
    "swiggy app",
    "swiggy dineout",
    "swiggy dineout restaurants",
    "uber",
    "weekday dining",
    "weekend dining",
    "zomato"
  ],
  travel: [
    "air tickets/hotels (smartbuy)",
    "airline miles conversion",
    "airline tickets",
    "airline/hotel booking via smartbuy",
    "airmiles",
    "all retail",
    "cashback",
    "cashback / smartbuy / airmiles",
    "catalogue",
    "dining",
    "etihad airways booking",
    "etihad airways offers",
    "etihad airways tickets",
    "flight & hotel vouchers",
    "flight + hotel voucher",
    "flights",
    "flights on intermiles.com",
    "flights via etihad",
    "flights via intermiles.com",
    "general travel",
    "hotel & flight booking via smartbuy mmt mybiz",
    "hotel & flight bookings via smartbuy mmt mybiz",
    "hotel booking",
    "hotel booking via intermiles.com",
    "hotel bookings via intermiles",
    "hotel bookings via intermiles.com",
    "hotels",
    "irctc",
    "irctc / utility / dining",
    "irctc bookings",
    "irctc via smartbuy",
    "itc hotel buffets",
    "itc hotels stay offers",
    "lounge access",
    "marriott bonvoy hotels",
    "mmt mybiz smartbuy",
    "mmt mybiz travel",
    "mobile recharge",
    "shopping",
    "smartbuy",
    "smartbuy portal",
    "smartbuy travel",
    "taxi rides",
    "train tickets",
    "train tickets (irctc)",
    "travel"
  ],
  
  grocery: [
  "ajio",
  "bigbasket",
  "bookmyshow",
  "dining",
  "dining and grocery",
  "easy emi",
  "flipkart wholesale platform",
  "grocery",
  "grocery and supermarkets",
  "grocery stores",
  "oyo",
  "payzapp",
  "select merchants (bigbasket",
  "shoppers stop vouchers",
  "shoppers stop weekend",
  "shoppers stop weekends",
  "smartbuy",
  "smartbuy platform",
  "supermarket",
  "swiggy",
  "uber",
  "uber)"
  ],

  electronics: [
  "accounting",
  "advertising",
  "cloud hosting",
  "electronics",
  "payzapp",
  "smartpay",
  "software license purchase",
  "utility bills"
  ],

  apparel: [
  "fashion",
  "luxury spa access",
  "premium partners",
  "quarterly milestone"
  ],

  others: [
  "000 monthly spend",
  "000+",
  "above ₹75",
  "all offline spends",
  "all other offline/online retail",
  "all other online transactions",
  "all other purchases",
  "all retail",
  "all retail spends",
  "all spends",
  "amazon",
  "annual milestone",
  "annual renewal",
  "annual spend",
  "annual spend benefits",
  "best price spend",
  "best price store spend",
  "bigbasket",
  "bill payments",
  "easy emi",
  "easyemi",
  "flights",
  "flipkart",
  "general",
  "general retail",
  "general spend",
  "harley-davidson dealers",
  "hotels (via payzapp & smartbuy)",
  "international spending",
  "monthly spend reward",
  "monthly spend ₹80",
  "neucoins redemption",
  "non-shoppers stop",
  "non-tata brands",
  "normal retail",
  "online",
  "online spends",
  "other expenses",
  "other paytm categories",
  "other regular spends",
  "other retail spends",
  "other retail transactions",
  "other spends including upi",
  "others",
  "payment convenience",
  "paytm spends",
  "payzapp",
  "pos (offline)",
  "pre-fund facility",
  "quarterly milestone",
  "quarterly spend",
  "quarterly spend benefit",
  "quarterly spend vouchers",
  "regular spends",
  "reliance smart",
  "retail",
  "retail shopping",
  "retail spends",
  "shoppers stop",
  "smartbuy",
  "sme special offers",
  "specific paytm categories",
  "spend based",
  "spend ₹8 lakh/year",
  "swiggy",
  "vendor payments",
  "vendor restrictions",
  "wallet loads",
  "weekday spends",
  "weekend spends",
  "welcome voucher",
  "working capital facility"
],

utilities: [
  "bill payment",
  "bill payment via payzapp & smartpay",
  "bill payments",
  "bill payments (payzapp",
  "bill payments via payzapp & smartpay",
  "bills",
  "business insurance package",
  "business productivity tools via smartbuy bizdeals",
  "business spend",
  "business tools via nuclei",
  "cash flow management",
  "category restrictions",
  "centralized account",
  "centralized expenses",
  "centralized payments",
  "centralized purchase",
  "comprehensive cover",
  "concierge services",
  "credit period",
  "credit period flexibility",
  "custom credit options",
  "dealer network enablement",
  "digital audit trail",
  "digital collection tool",
  "digital platform",
  "electricity",
  "emi / interest",
  "emi spends",
  "erp integration",
  "erp mis integration",
  "extended credit",
  "fraud protection",
  "gas",
  "government payments",
  "govt",
  "govt. tax",
  "gst",
  "gst payment via payment.gst.gov.in",
  "gst payments",
  "income tax",
  "income tax payment via eportal.incometax.gov.in",
  "interest free days",
  "interest-free days",
  "linked to upi apps",
  "lost card liability",
  "lost card protection",
  "merchant restrictions",
  "mmt mybiz",
  "mobile recharge",
  "procurement payments",
  "rebate benefits",
  "receivables optimization",
  "smartpay utility bills",
  "smartpay)",
  "software tools",
  "supermarkets",
  "tax",
  "tax payments",
  "telecom",
  "transaction consolidation",
  "upgrade",
  "upi payments",
  "upi spends",
  "upi transactions",
  "utilities",
  "utility",
  "utility bills",
  "water",
  "water bill payments",
  "water bills",
  "zero lost card liability"
 ],

 fuel: [
  "all fuel stations",
  "all fuel transactions",
  "all stations",
  "annual spend",
  "bill payments",
  "e-commerce",
  "e-commerce & pos",
  "fleet fuel management",
  "fuel",
  "fuel spends",
  "fuel station",
  "fuel stations",
  "fuel surcharge waiver",
  "fuel transactions",
  "fuel waiver",
  "indianoil fuel",
  "petrol pumps",
  "petrol spend",
  "renewal fee waiver"
],

cashback: [
  "000",
  "activation bonus",
  "first 2 transactions",
  "first 90 days",
  "foreign currency transactions",
  "gift vouchers",
  "joining",
  "milestone",
  "milestone reward points",
  "milestone spends",
  "monthly spends above ₹50",
  "neupass tata neu offers",
  "non-tata brands",
  "online spends (specific mccs)",
  "paytm",
  "paytm app (select merchants)",
  "pos & wallet loads",
  "quarterly milestone",
  "redemption against statement",
  "regular retail",
  "renewal bonus",
  "retail purchases",
  "retail shopping",
  "revolving credit",
  "reward",
  "select paytm categories",
  "select paytm spends",
  "tata neu + partner brands",
  "tata neu + tata brands",
  "teacher's day",
  "voucher earning"
],

membership: [
  "family members",
  "gift vouchers + memberships",
  "joining gift",
  "membership + free night",
  "membership benefit",
  "welcome benefit"
],
lounge: [
  "airport lounge",
  "airport lounge access",
  "domestic",
  "domestic lounge access",
  "fast track airport service",
  "international + domestic",
  "irctc executive lounge access",
  "lounge",
  "lounge access",
  "priority pass + visa/mastercard lounge access",
  "priority pass access"
],

insurance: [
  "accidental / hospitalization cover",
  "accidental/medical cover",
  "air accident",
  "air accident + medical cover",
  "card safety",
  "comprehensive cover",
  "comprehensive protection",
  "doctor’s professional insurance",
  "hospitalization",
  "indemnity insurance",
  "liability",
  "lost card",
  "medical",
  "overseas medical",
  "professional indemnity cover",
  "travel",
  "travel & medical cover",
  "travel accident cover",
  "travel insurance",
  "travel/health/credit shield",
  "travel/medical/credit shield",
  "vehicle premiums"
],

  

};
